### ISSUE TITLE
Tls is missing

### ISSUE THREAD

**Issue by 0x8f701** [PsiACE/casbin-raft-immature#1]
Tls is a very important part in casbin-raft, if it's not ok then we'll not be able to use casbin-raft as a cluster, we can only use it in single-node environment.

We should use grpc + tls, I would prefer using native-tls than rustls, because it supports more certificates.

Another question is, do we need to have tls implemented in casbin-raft, can we use other services to do this like nginx? Since I have nerver tried to do this, I have no idea for now

**Comment by 0x8f701** [comment]
here is an example: https://github.com/hyperium/tonic/blob/master/examples/src/tls/client.rs and https://github.com/GopherJ/cfg/blob/master/cert/gen-cert.sh is a script that I use for tls communication in for example mqtt

**Comment by GopherJ** [comment]
Another question is: do we really need to have this in casbin-raft instead of upper level?

**Comment by PsiACE** [comment]
Maybe you can check the `tls` branch, I think this may provide the ability to support tls.

At least one thing that can be confirmed is that we can use the tls support provided by tonic.

**Comment by 0x8f701** [comment]
@PsiACE Thanks I think it's enough, tonic uses `rustls` internally
