### ISSUE TITLE
small problems

### ISSUE THREAD

**Issue by 0x8f701** [PsiACE/casbin-raft-immature#2]
1. https://github.com/PsiACE/casbin-raft-immature/blob/66a827f93fb8ff9c7c7a6e97392189503c1bb13d/src/logger.rs#L46 may cause memory leak, why not do directly `match &*log_level.to_lowercase()`?

if every call of log needs to leak a string, it'll be a problem

same here: https://github.com/PsiACE/casbin-raft-immature/blob/66a827f93fb8ff9c7c7a6e97392189503c1bb13d/src/node.rs#L285, it worth noting creating a real enum will be better than matching over string, `op` is can be changed to a real enum

**Comment by 0x8f701** [comment]
2. two depencies can be removed
    - dashmap
    - http

**Comment by 0x8f701** [comment]
3. https://github.com/PsiACE/casbin-raft-immature/blob/66a827f93fb8ff9c7c7a6e97392189503c1bb13d/src/lib.rs#L12 casbin-raft should export its own error type and result which should be a superset of casbin::Error, casbin::Result

See also: https://github.com/PsiACE/casbin-raft-immature/blob/66a827f93fb8ff9c7c7a6e97392189503c1bb13d/src/network.rs#L59

**Comment by 0x8f701** [comment]
4. since you are using thiserror, why not use auto from implementation provided by thiserror? eg. `#[from] xxx` than implement it manually. Also it's maybe better to avoid `to_string` but keep the real error behind

**Comment by PsiACE** [comment]
1. Done, now we have `match &*log_level.to_lowercase()` & real enum for `op`
2. Why? They are used in the code.
3. Put it aside for now, `Error` -> `StorageError`, clearer.
4. Done, I like this. `#[error(transparent)] CasbinError(#[from] CasbinErrors),`

**Comment by 0x8f701** [comment]
@PsiACE in your code, http has only be used for `uri` if I remembered correctly, tonic accepts also `&str` so I think we can remove this dependency.

When it comes to `dashmap`, I think we will not have many nodes so I think it won't help a lot

**Comment by PsiACE** [comment]
Ok, but keep them for now, I will clean up the code later.

**Comment by PsiACE** [comment]
Now consider checking the `stable` branch, I integrated all the changes. All the issues mentioned in this question have been completed, except for the need for more delicate error handling.
