### ISSUE TITLE
[feature request] add RemoveFilteredPolicy, RemovePolicies, AddPolicies service

### ISSUE THREAD

**Issue by 0x8f701** [PsiACE/casbin-raft-immature#3]
RemoveFilteredPolicy + batch operations are quite important so I think it worth adding them

**Comment by PsiACE** [comment]
According to the previous meeting discussion and enhancement proposal draft, we should implement the following functions for sync policies:

- add_policies
- remove_policies
- remove_filtered_policy
- clear_policy

Therefore, I removed the previous add_policy & remove_policy and implemented the functions mentioned above.

**Comment by 0x8f701** [comment]
@PsiACE I think we need all including `add_policy` & `remove_policy` because there are two cases, most of the time we will use `add_policy` and `remove_policy`, sometimes we need batch operations

**Comment by PsiACE** [comment]
Ok, now we also have `add_policy` and `remove_policy`
